(* Read a graph from a file,
 * Write a graph to a file. *)

open Graph

type path = string

(* Values are read as strings. *)
val from_file: path -> string graph

(* Similarly, we write only a string graph.
 * If necessary, use gmap (to be written by you) to prepare the input graph. *)
val write_file: path -> string graph -> unit


(* The format of files is compatible with the files generated by:
   https://algorithms.discrete.ma.tum.de/graph-algorithms/flow-ford-fulkerson/index_en.html
*)

let export gr source sink chemin=
   let ff = open_out chemin in
   fprintf ff "digraph finite_state_machine {\n";
   fprintf ff "\tfontname=\"Helvetica,Arial,sans-serif\"\n";
   fprintf ff "\tnode [fontname=\"Helvetica,Arial,sans-serif\"]\n";
   fprintf ff "\tedge [fontname=\"Helvetica,Arial,sans-serif\"]\n";
   fprintf ff "\trankdir=LR;\n";
   fprintf ff "\tnode [shape = doublecircle]; %d %d;\n" source sink;
   fprintf ff "\tnode [shape = circle];\n";

   e_iter gr (fun arc -> fprintf ff "\t%d -> %d [label = \"%s\"];\n" arc.src arc.tgt arc.lbl );

   fprintf ff "}\n";
   close_out ff;;
